# This version use larger decoder_rnn_dim and more decoder_rnn layers
data:
  #train_fid_list: "../wavernn-vc/dump/vc_train_set/f0s.scp"
  train_fid_list: "/home/shaunxliu/data/vctk/fidlists/train_fidlist.new"
  dev_fid_list: "/home/shaunxliu/data/vctk/fidlists/dev_fidlist.new"
  eval_fid_list: "/home/shaunxliu/data/vctk/fidlists/eval_fidlist.txt"
  vctk_ppg_dir: "/home/shaunxliu/data/vctk/conformer_bnf10ms"
  libri_ppg_dir: "/home/shaunxliu/data/LibriTTS/conformer_bnf10ms"
  vctk_f0_dir: "/home/shaunxliu/data/vctk/merged_f0s"
  libri_f0_dir: "/home/shaunxliu/data/LibriTTS/f0s"
  vctk_wav_dir: "/home/shaunxliu/data/vctk/wav_mono_24k_16b_norm-6db"
  libri_wav_dir: "/home/shaunxliu/data/LibriTTS/LibriTTS/train-wavs-clean460/"
  vctk_spk_dvec_dir: "/home/shaunxliu/data/vctk/GE2E_spkEmbed_step_5805000_perSpk"
  libri_spk_dvec_dir: "/home/shaunxliu/data/LibriTTS/GE2E_spkEmbed_step_5805000_perSpk"
  ppg_file_ext: "ling_feat.npy"
  f0_file_ext: "f0.npy"
  wav_file_ext: "wav"
  min_max_norm_mel: false
  mel_min: -12.0
  mel_max: 2.5 
  #pretrain_model_file: "./ckpt/seq2seq_mol_ppg2mel_vctk_v2_add_arctic_IN_seed0/best_loss_step_48000.pth"

hparas:
  batch_size: 32
  valid_step: 2000
  max_step: 1000000
  optimizer: 'Adam'
  lr: 0.001
  eps: 1.0e-8
  weight_decay: 1.0e-6
  lr_scheduler: 'warmup'   # "fixed", "warmup"

model_name: "seq2seqmol"
model:
  num_speakers: 1250
  spk_embed_dim: 256
  bottle_neck_feature_dim: 144
  attention_rnn_dim: 256
  attention_dim: 256
  decoder_rnn_dim: 256
  num_decoder_rnn_layer: 1
  concat_context_to_last: True
  prenet_dims: [256, 128]
  prenet_dropout: 0.5
  num_mixtures: 5
  frames_per_step: 2
  postnet_num_layers: 5
  postnet_hidden_dim: 512
  mask_padding: True
  use_bnf_prenet: True
  use_pitch_info: True
  use_spk_dvec: True
  use_instance_norm: True 
